antora:
  extensions:
  - require: antora-navigator-extension
    config_file: ./antora-navigator.yml
  - id: unlisted-pages
    enabled: true
    require: ./lib/unlisted.js
site:
  title: Документация Docsvision
  url: /
#  start_page: current@system::index.adoc
  robots: allow
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:from
#  latest_prerelease_version_segment: dev
  html_extension_style: indexify
content:
  branches: [dev, '5.5.*', '6.1*', main, 'GBL-*', 'SUP-*', 'CU*']
  edit_url: ~
  sources:
#    - url: https://github.com/Docsvision/antora-product-changes.git
#      branches: [dev]
    - url: https://github.com/Docsvision/antora-start-page.git
    - url: https://github.com/Docsvision/antora-web-client.git
    - url: https://github.com/Docsvision/antora-worker-service.git
    - url: https://github.com/Docsvision/antora-platform.git
    - url: https://github.com/Docsvision/antora-management-console.git
    - url: https://github.com/Docsvision/antora-install-guide.git
    - url: https://github.com/Docsvision/antora-designers-and-directories.git
    - url: https://github.com/Docsvision/antora-system-description.git
      branches: [dev, 'GBL-*']
    - url: https://github.com/Docsvision/antora-approval-designer.git
    - url: https://github.com/Docsvision/antora-back-office.git
    - url: https://github.com/Docsvision/antora-upgrade-guide.git
      branches: [dev, 'GBL-*', dv6_CU3, dv6_CU2, 'dv5_GBL-*']
    - url: https://github.com/Docsvision/antora-engineer-guide.git
      branches: [dev, 'GBL-*', dev_m4d-scenarios]
    - url: https://github.com/Docsvision/antora-programmer-guide.git
      branches: [dev, 'GBL-*', dv6_CU3]
    - url: https://github.com/Docsvision/antora-windows-client.git
    - url: https://github.com/Docsvision/antora-document-management.git
    - url: https://github.com/Docsvision/antora-schemas-description.git
    - url: https://github.com/Docsvision/antora-solution-manager.git
    - url: https://github.com/Docsvision/antora-workflow.git
    - url: https://github.com/Docsvision/antora-archive-management.git
    - url: https://github.com/Docsvision/antora-edi.git
    - url: https://github.com/Docsvision/antora-resource-kit.git
    - url: https://github.com/Docsvision/antora-install-linux.git
    - url: https://github.com/Docsvision/antora-take-office.git
    - url: https://github.com/Docsvision/antora-m4d-registry-integration.git
    - url: https://github.com/Docsvision/antora-kontur-integration.git
    - url: https://github.com/Docsvision/antora-directory-replication.git
    - url: https://github.com/Docsvision/antora-branch-exchange.git
    - url: https://github.com/Docsvision/antora-conversion-service.git
    - url: https://github.com/Docsvision/antora-template-designer.git
    - url: https://github.com/Docsvision/antora-notification-service.git
ui:
#  supplemental_files:
#    - path: js/nav.js
#      contents: ./node_modules/antora-navigator-extension/data/js/nav.js
  supplemental_files: ./node_modules/antora-navigator-extension/data/
  bundle:
    url: ./build/ui-bundle.zip
asciidoc:
  attributes:
    sectids: ''
    sectanchors: ''
    icons: font
    page-pagination: ''
    toclevels: 10
    experimental: ''
    idprefix: ''
    idseparator: '-'
    toc-title: 'Содержание'
    figure-caption: 'Рисунок'
    table-caption: 'Таблица'
    appendix-caption: 'Приложение'
    example-caption: 'Пример'
    kroki-default-format: 'svg'
    kroki-fetch-diagram: 'true'
    warning-caption: 'ОСТОРОЖНО'
    caution-caption: 'ВНИМАНИЕ'
    tip-caption: 'СОВЕТ'
    note-caption: 'ПРИМЕЧАНИЕ'
    important-caption: 'ВАЖНО'
    cns: 'Консоль настройки Docsvision'
    dispatch: 'Диспетчер служб IIS'
    dv: 'Docsvision'
    root-cert: 'Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователя.footnote:[Например, корневой сертификат КриптоПро]@'
    sss: 'Docsvision 5.5 Storage Server'
    fts: 'Docsvision 5.5 Full-Text indexing Service'
    wfs: 'Docsvision 5.5 Workflow Server'
    fss: 'Docsvision 5.5 File Service'
    wss: 'Docsvision 5.5 Worker Service'
    wacs: 'Docsvision Management Console Service'
    wacss: 'Docsvision Settings Service'
    sss-new: 'dvappserver'
    fts-new: 'dvfulltextservice'
    wfs-new: 'dvworkflow'
    fss-new: 'dvfileservice'
    wss-new: 'dvworkerservice'
    wacs-new: 'dvconsole'
    wacss-new: 'dvsettings'
    wcs-new: 'dvwebclient'
    extapi-new: 'dvexternalapi'
    pl: 'Платформа'
    wincl: 'Windows-клиент'
    wc: 'Web-клиент'
    ws: 'фоновых операций'
    of-ws: 'фоновой операции'
    is-ws: 'фоновая операция'
    kvr: 'Конструктор Web-разметок'
    ad: 'Конструктор согласований'
    dm: 'Управление документами'
    bo: 'Базовые объекты'
    wf: 'Управление процессами@'
    to: 'Делопроизводство 4.5'
    es: 'Elasticsearch'
    em: 'Модуль интеграции с операторами ЭДО'
    rk: 'Resource Kit'
    am: 'Управление архивом'
    sm: 'Менеджер решений'
    of-sm: 'Менеджера решений'
    hklm-dv: 'HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision'
    hklm: 'HKEY_LOCAL_MACHINE'
    service: 'специальный сервис логики этапа'
    of-service: 'специального сервиса логики этапа'
    c-service: 'Специальный сервис логики этапа'
    sett-serv: 'Сервис настроек'
    of-sett-serv: 'Сервиса настроек'
    to-sett-serv: 'Сервису настроек'
    mc: 'Консоль управления Docsvision'
    of-mc: 'Консоли управления Docsvision'
    dv-admins-serv: 'DocsVision Administrators'
    dv-sec-admins-serv: 'DocsVision Security Administrators'
    dv-arch-ops-serv: 'DocsVision Archive Operators'
    dv-solution-admins-serv: 'Docsvision SolutionManager Administrators'
    dv-web-admin-cns-admins-serv: 'Docsvision Management Console Administrators'
    dv-sett-serv-admins-serv: 'Docsvision SettingsService Administrators'
    dv-wf-creators-serv: 'Docsvision Workflow Process Creators'
    dv-wf-creators-dir: 'Создатели бизнес-процессов'
    dv-search-creators-serv: 'Docsvision Search Query Creators'
    dv-search-creators-dir: 'Создатели поисковых запросов'
    dv-users-serv: 'DocsVision Users'
    dv-sec-admins-dir: 'Администраторы безопасности'
    dv-arch-ops-dir: 'Операторы архива'
    dv-admins-dir: 'Администраторы'
    dv-ad-admins-dir: 'Администраторы КС'
    dv-sys-wf-dir: 'Системная для WF'
    dv-power-users-serv: 'DocsVision Power Users'
    dv-dm-admins-dir: 'Администраторы УД'
    mssql: 'Microsoft SQL@'
    pgsql: 'PostgreSQL@'
    tspcom-v: '2.0 и выше'
    ocspcom-v: '2.0 и выше'
    cadescom-v: '2.0.13292 и выше'
    csp-v: '5.0 и выше'
    l-1: '1.7'
    l-1-1: '1.8.1'
    l-2: '22.04 (LTS)'
    l-3: '20.04 (LTS)'
    l-4: '11 (stable)'
    l-5: '10 (oldstable)'
    asp-bundle: 'ASP.NET Core Runtime (Hosting Bundle) версии  6.0.3@'
    net-r: '.NET Desktop Runtime (x86/x64) версии 6.0.3@'
    config: 'appsettings@'
    ms: 'Microsoft'
    pg: 'Postgres'
    long: 'CADES-X Long Type 1'
    bes: 'CADES-BES'
    chrome-v: 'Google Chrome 109 и выше'
    edge-c: 'Microsoft Edge 109 и выше'
    chromium-v: '114.0.5735 и выше'
    edge-v: '44.17763.1.0 и выше'
    yandex: 'Яндекс.Браузер 23 и выше'
    safari: 'Safari 16 и выше'
    ms-sql-v-1: '2019, редакции: Enterprise, Standard, Developer Edition'
    ms-sql-v-2: '2017, редакции: Enterprise, Standard, Developer Edition'
    ms-sql-v-3: '2016, редакции: Enterprise, Standard, Developer Edition'
    ms-sql-v-4: '2016 должно быть установлено обновление https://support.microsoft.com/en-us/help/3205052/cumulative-update-4-for-sql-server-2016[Cumulative Update 4 for SQL Server] или более новое'
    ms-sql-v-5: '2016 SP1 должно быть установлено обновление https://support.microsoft.com/en-us/help/4013106/cumulative-update-2-for-sql-server-2016-sp1[Cumulative Update 2 for SQL Server 2016 SP1] или более новое'
    pg-sql-v-1: 'PostgreSQL версии 12'
    pg-sql-v-2: 'Postgres Pro версии 12'
    tt-sql-v: 'Tantor BE версии 15.4.3'
    tt: 'Tantor'
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'
output:
  dir: wwwroot
runtime:
  fetch: true
