site:
  title: Docsvision Documentation
  url: http://doc-online.vdv.digdes.com:5000/
  start_page: 5.5.16@webclient:ROOT:annotation.adoc
  robots: allow
urls:
  latest_version_segment: 'latest'
  latest_version_segment_strategy: redirect:to
  html_extension_style: indexify
content:
  branches: '5.5.16'
  edit_url: ~
  sources:
    - url: https://ddsm-gitlab.digdes.com/documentation/dv/docs-online/WebC.git
git:
  credentials:
    path: ~/.git-credentials
ui:
  bundle:
    url: ./build/ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ search.html ]
    - path: search.html
      contents: |
        <!DOCTYPE html>
        <html lang="ru">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <title>Поиск по документации Docsvision :: Docsvision Documentation</title>
            <link rel="canonical" href="http://doc-online.vdv.digdes.com:5000/search.html">
            <meta name="generator" content="Antora 2.3.4">
            <link rel="stylesheet" href="/_/css/site.css">
            <script>var uiRootPath = '/_'</script>
        	<script async src="/_/js/vendor/fess-ss.min.js"></script>
          </head>
          <body class="article">
        <header class="header">
          <nav class="navbar">
            <div class="navbar-brand">
              <a class="navbar-item" href="http://doc-online.vdv.digdes.com:5000">Docsvision Documentation</a>
              <button class="navbar-burger" data-target="topbar-nav">
                <span></span>
                <span></span>
                <span></span>
              </button>
            </div>
            <div id="topbar-nav" class="navbar-menu">
              <div class="navbar-end">
                <div class="navbar-item hide-for-print">
               	  <form action="/search.html" method="get">
               		<input type="text" name="q" placeholder="Поиск">
               		<input type="submit" value="Поиск">
               	  </form>
                </div>
                <a class="navbar-item" href="#">Домой</a>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link" href="#">Купить</a>
                  <div class="navbar-dropdown">
                    <a class="navbar-item" href="#">Платформа</a>
                    <a class="navbar-item" href="#">Web-клиент</a>
                    <a class="navbar-item" href="#">Базовые объекты</a>
                  </div>
                </div>
                <a class="navbar-item" href="#">Любой контент</a>
              </div>
            </div>
          </nav>
        </header>
        <div class="body">
        <article class="doc">
              <h1 class="page">Поиск по документации</h1>
        <div class="paragraph">
        <script>
          (function() {
            var fess = document.createElement('script');
            fess.type = 'text/javascript';
            fess.async = true;
            // Set the URL of FSS JS to src
            fess.src = 'http://192.168.56.136:5000/_/js/vendor/fess-ss.min.js';
            fess.charset = 'utf-8';
            fess.setAttribute ('id', 'fess-ss');
            // Set the URL of Fess search API to fess-url
            fess.setAttribute ('fess-url', 'http://192.168.56.136:8080/json');
            var s = document.getElementsByTagName ('script') [0];
            s.parentNode.insertBefore (fess, s);
          }) ();
        </script>
        <fess:search></fess:search>
        </div>
        </article>
        </div>
        </main>
        <footer class="footer">
          <p>Любой другой текст или даже картинки-иконки и т.п.</p>
        </footer>
        <script src="/_/js/site.js"></script>
        <script async src="/_/js/vendor/highlight.js"></script>
          </body>
        </html>
asciidoc:
  attributes:
    sectids: ''
    sectlinks: ''
    sectanchors: ''
    icons: font
    page-pagination: ''
    toclevels: 10
    experimental: ''
    source-highlighter: highlightjs
    toc-title: Содержание
    figure-caption: Рисунок
    table-caption: Таблица
    appendix-caption: Приложение
    example-caption: Пример
output:
  dir: wwwroot
runtime:
  fetch: true
