antora:
  extensions:
  - require: antora-navigator-extension
    config_file: ./antora-navigator.yml
  - id: unlisted-pages
    enabled: true
    require: ./lib/unlisted.js
site:
  title: Документация Docsvision
  url: https://help.docsvision.com/
  robots: allow
urls:
#  latest_version_segment: latest
#  latest_version_segment_strategy: redirect:to
  latest_prerelease_version_segment: dev
  html_extension_style: indexify
content:
  branches: 'dev'
  edit_url: ~
  sources:
    - url: https://github.com/Docsvision/WebC-Antora.git
    - url: https://github.com/Docsvision/Worker-Antora.git
    - url: https://github.com/Docsvision/Platform-Antora.git
    - url: https://github.com/Docsvision/WebAC-Antora.git
    - url: https://github.com/Docsvision/Install-Guide-Antora.git
    - url: https://github.com/Docsvision/Designers-And-Directories-Antora.git
    - url: https://github.com/Docsvision/System-Antora.git
    - url: https://github.com/Docsvision/Approval-Designer-Antora.git
    - url: https://github.com/Docsvision/Base-Objects-Antora.git
    - url: https://github.com/Docsvision/Platform-Upgrade-Antora.git
    - url: https://github.com/Docsvision/Engineer-Antora.git
    - url: https://github.com/Docsvision/Programmer-Antora.git
    - url: https://github.com/Docsvision/Windows-Client-Antora.git
    - url: https://github.com/Docsvision/Document-Management-Antora.git
    - url: https://github.com/Docsvision/Schemas-Antora.git
ui:
#  supplemental_files:
#    - path: js/nav.js
#      contents: ./node_modules/antora-navigator-extension/data/js/nav.js
  supplemental_files: ./node_modules/antora-navigator-extension/data/
  bundle:
    url: ./build/ui-bundle.zip
asciidoc:
  attributes:
    sectids: ''
    sectanchors: ''
    icons: font
    page-pagination: ''
    toclevels: 10
    experimental: ''
    idprefix: ''
    idseparator: '-'
    toc-title: 'Содержание'
    figure-caption: 'Рисунок'
    table-caption: 'Таблица'
    appendix-caption: 'Приложение'
    example-caption: 'Пример'
    kroki-default-format: 'svg'
    kroki-fetch-diagram: 'true'
    warning-caption: 'ОСТОРОЖНО'
    caution-caption: 'ВНИМАНИЕ'
    tip-caption: 'СОВЕТ'
    note-caption: 'ПРИМЕЧАНИЕ'
    important-caption: 'ВАЖНО'
    cns: 'Консоль настройки Docsvision'
    dispatch: 'Диспетчер служб IIS'
    dv: 'Docsvision'
    root-cert: 'Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователя.footnote:[Например, корневой сертификат КриптоПро]@'
    pl: 'Платформа'
    wincl: 'Windows-клиент'
    wc: 'Web-клиент'
    sss: 'Docsvision 5.5 Storage Server'
    fts: 'Docsvision 5.5 Full-Text indexing Service'
    wfs: 'Docsvision 5.5 Workflow Server'
    fss: 'Docsvision 5.5 File Service'
    wss: 'Docsvision 5.5 Worker Service'
    wacs: 'Docsvision Management Console Service'
    wacss: 'Docsvision Settings Service'
    ws: 'фоновых операций'
    kvr: 'Конструктор Web-разметок'
    ad: 'Конструктор согласований'
    dm: 'Управление документами'
    bo: 'Базовые объекты'
    wf: 'Управление процессами@'
    es: 'Elasticsearch'
    hklm-dv: 'HKEY_LOCAL_MACHINE\SOFTWARE\Docsvision'
    hklm: 'HKEY_LOCAL_MACHINE'
    service: 'специальный сервис логики этапа'
    of-service: 'специального сервиса логики этапа'
    c-service: 'Специальный сервис логики этапа'
    sett-serv: 'Сервис настроек'
    of-sett-serv: 'Сервиса настроек'
    to-sett-serv: 'Сервису настроек'
    mc: 'Консоль управления Docsvision'
    of-mc: 'Консоли управления Docsvision'
    dv-admins-serv: 'DocsVision Administrators'
    dv-sec-admins-serv: 'DocsVision Security Administrators'
    dv-arch-ops-serv: 'DocsVision Archive Operators'
    dv-solution-admins-serv: 'Docsvision SolutionManager Administrators'
    dv-web-admin-cns-admins-serv: 'Docsvision Management Console Administrators'
    dv-sett-serv-admins-serv: 'Docsvision SettingsService Administrators'
    dv-wf-creators-serv: 'Docsvision Workflow Process Creators'
    dv-wf-creators-dir: 'Создатели бизнес-процессов'
    dv-search-creators-serv: 'Docsvision Search Query Creators'
    dv-search-creators-dir: 'Создатели поисковых запросов'
    dv-users-serv: 'DocsVision Users'
    dv-sec-admins-dir: 'Администраторы безопасности'
    dv-arch-ops-dir: 'Операторы архива'
    dv-admins-dir: 'Администраторы'
    dv-ad-admins-dir: 'Администраторы КС'
    dv-sys-wf-dir: 'Системная для WF'
    dv-power-users-serv: 'DocsVision Power Users'
    mssql: 'Microsoft SQL@'
    pgsql: 'PostgreSQL@'
    sm: 'Менеджер решений'
    of-sm: 'Менеджера решений'
  extensions:
  - asciidoctor-kroki
output:
  dir: wwwroot
runtime:
  fetch: true
